### ISSUE TITLE
Uncaught Exception on running the App

### ISSUE THREAD

**Issue by PrincessAkira** [eythaann/Komorebi-UI#1]
Happens when freshly installed and then everytime i open it.

![image](https://github.com/eythaann/Komorebi-UI/assets/45071533/a4c95c72-4b1b-4aef-9d1c-bc523eb47444)

**Comment by eythaann** [comment]
@PrincessAkira are you using the last version? and can you share the settings.json file please

**Comment by PrincessAkira** [comment]
> @PrincessAkira are you using the last version?

Yes.

Here is the settings file aswell
[settings.json](https://github.com/eythaann/Komorebi-UI/files/14396318/settings.json)

**Comment by eythaann** [comment]
delete it, and try start again, but how this happen 🤔 because the file is only created at save

**Comment by eythaann** [comment]
Lol I replicated, I will fixed now

**Comment by eythaann** [comment]
@PrincessAkira download the [update](https://github.com/eythaann/Komorebi-UI/releases/tag/v1.0.0-beta.7) , also delete the empty file to start again.
