### ISSUE TITLE
Problem app start up

### ISSUE THREAD

**Issue by 4rafi** [eythaann/Komorebi-UI#2]
i tried downloading and installing the prereleased ver. 9 & 10, both have error when opening the program as below:
![image](https://github.com/eythaann/Komorebi-UI/assets/96292194/79162418-1d1a-4387-b69f-91fc04cbd6b8)

and the window tiling is not activated its make the apps unusable so i cant try this software. please help or fix this.

**Comment by eythaann** [comment]
@4rafi  hmm your real user folder is Window10?

**Comment by 4rafi** [comment]
> @4rafi hmm your real user folder is Window10?

Yeah my friend installed the windows for me years ago, and I don't bother changing the profile name

**Comment by 4rafi** [comment]
Accidentally closed the issue when replying via mobile

**Comment by eythaann** [comment]
haha
fixed on: 62f7865639422ed9f7864264979d1d55181ec821
uploaded to: [v1.0.0-prerelease.11](https://github.com/eythaann/Komorebi-UI/releases/tag/v1.0.0-prerelease.11)

**Comment by 4rafi** [comment]
the error is gone now, but nothing is happening 
![image](https://github.com/eythaann/Komorebi-UI/assets/96292194/75edfa2b-8a7c-4947-8f8a-5aec950169ca)

**Comment by eythaann** [comment]
go to information > force restart, or right click on the tray icon > restart

**Comment by 4rafi** [comment]
Tried both and restarting the PC but unfortunately nothing happen.

**Comment by eythaann** [comment]
No komorebi is included in the installer.
Q: do you have installed AHK? may be is that
I have no test that 🤔

**Comment by eythaann** [comment]
hmm noup it still works without ahk installed
![image](https://github.com/eythaann/Komorebi-UI/assets/76607907/493b2325-7737-4ba0-90f9-8838691ead1d)

**Comment by eythaann** [comment]
@4rafi if you run manually komorebi-wm start komorebi normally?

![image](https://github.com/eythaann/Komorebi-UI/assets/76607907/212a7d27-6085-4773-99d1-78b4b321492f)

**Comment by eythaann** [comment]
This is a komorebi wmanager bug, so I will close this ticket this is fixed on it, I will cherry pick all 0.1.23 and create a new prerelease.

https://github.com/LGUG2Z/komorebi/commit/d52715a8faebb355d98cf346793bc71f822acfae

**Comment by 4rafi** [comment]
Okay thank you for your effort

**Comment by 4rafi** [comment]
based on commit that eythaan link, doing this fix my problem: 

If you are installing `komorebi` for the first time on a new machine, create a
dedicated folder for `komorebi` in `$Env:LOCALAPPDATA`.

```powershell
mkdir "$Env:LOCALAPPDATA\komorebi" -ea 0
```

**Comment by eythaann** [comment]
since [prerelease 12](https://github.com/eythaann/Komorebi-UI/releases/tag/v1.0.0-prerelease.12) this folder is always ensured to exist before running the app.
